# Generated by Django 4.2.3 on 2023-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_songs_alter_student_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='universities', to='app1.teacher'),
        ),
    ]
